import React,{useEffect,useMemo,useState} from 'react';
import{createRoot}from'react-dom/client';
import{ArrowLeft,ArrowUpRight,Bookmark,BriefcaseBusiness,CalendarDays,Check,ChevronDown,Clock3,Compass,ExternalLink,Globe2,MapPin,Mic2,Podcast,Search,Settings2,Sparkles,Trophy,UserRound,UsersRound,X}from'lucide-react';
import'./styles.css';

const opportunities=[
 {id:1,title:'Future of Work Summit 2026',org:'WorkForward Institute',category:'Conferences',icon:'conference',score:94,location:'Chicago, IL',format:'In person',value:'Potentially Paid',deadline:'Sep 28, 2026',date:'November 12–13, 2026',status:'new',new:true,why:'Exceptional match for your expertise in organizational transformation and future-ready leadership.',fit:{Expertise:96,Goals:94,Audience:91,Value:88,Probability:82},themes:['Future-ready leadership','Human-centered transformation','AI & the modern workforce'],gaps:'Highly competitive selection process; a distinctive point of view will be important.',looking:'Practitioners with a clear, evidence-backed perspective on how leaders can help organizations adapt to rapid workplace change.',prior:'Recent speakers include transformation executives from Adobe, Deloitte, and Atlassian, alongside independent workplace researchers.',pitch:'The Human Advantage: Leading Transformation When Technology Moves Faster Than Culture',approach:'Position your operating experience as the bridge between high-level transformation strategy and the daily decisions leaders actually need to make.'},
 {id:2,title:'The Modern Leader Podcast — Guest Call',org:'Northstar Media',category:'Podcasts & Media',icon:'podcast',score:89,location:'Remote',format:'Remote',value:'Unpaid / Visibility',deadline:'Oct 10, 2026',date:'Rolling interviews',status:'new',new:true,why:'The show’s executive audience aligns directly with your leadership and change expertise.',fit:{Expertise:92,Goals:96,Audience:94,Value:75,Probability:88},themes:['Modern leadership','Career reinvention','Leading through ambiguity'],gaps:'No direct fee; value depends on reach and repurposing the appearance.',looking:'Experienced operators who can share useful, personal stories—not generic leadership advice.',prior:'Recent guests include Fortune 500 people leaders, bestselling authors, and organizational psychologists.',pitch:'What transformation plans miss: the three human decisions that determine whether change sticks',approach:'Lead with one counterintuitive lesson and anchor it in a candid, high-stakes transformation story.'},
 {id:3,title:'Digital Transformation Excellence Awards',org:'Global Business Council',category:'Awards & Recognition',icon:'award',score:86,location:'Global',format:'Online submission',value:'Unpaid / Visibility',deadline:'Oct 18, 2026',date:'Winners announced January 2027',status:'saved',new:true,why:'Your transformation track record provides strong evidence for the Leadership Impact category.',fit:{Expertise:94,Goals:91,Audience:87,Value:82,Probability:73},themes:['Measurable transformation','Inclusive innovation','Leadership impact'],gaps:'The entry requires quantified business outcomes and two supporting references.',looking:'Clear evidence of durable business impact, original leadership, and benefits beyond implementation.',prior:'Winning entries consistently use specific before-and-after metrics and customer or employee validation.',pitch:'Transformation as a capability, not a project: building an organization that keeps adapting',approach:'Frame the submission around one measurable system-level change, supported by three concise proof points.'},
 {id:4,title:'Executive Leadership Workshop Facilitator',org:'Meridian Health Partners',category:'Paid Speaking',icon:'mic',score:83,location:'Boston, MA',format:'Hybrid',value:'Paid',compensation:'$7,500–$10,000',deadline:'Sep 30, 2026',date:'December 4, 2026',status:'new',new:true,why:'Strong topic alignment and a high-value audience, with a manageable customization requirement.',fit:{Expertise:89,Goals:86,Audience:88,Value:94,Probability:68},themes:['Leading change','Executive alignment','Decision velocity'],gaps:'Healthcare experience is preferred and travel is required for the final session.',looking:'An experienced facilitator who can turn leadership concepts into a practical half-day working session.',prior:'Past facilitators combine a concise keynote with peer exercises and an executive action plan.',pitch:'From alignment to action: the leadership operating system for complex change',approach:'Offer a modular workshop and emphasize how you adapt examples to regulated environments.'},
 {id:5,title:'Visiting Executive Speaker Series',org:'Kellerman School of Management',category:'Visibility Speaking',icon:'visibility',score:78,location:'New York, NY',format:'In person',value:'Unpaid / Visibility',deadline:'Nov 1, 2026',date:'Spring 2027',status:'new',new:false,why:'Excellent audience fit and credibility value, though there is no speaker fee.',fit:{Expertise:84,Goals:88,Audience:93,Value:69,Probability:76},themes:['Executive careers','Organizational change','Responsible leadership'],gaps:'No honorarium is listed and the date may require travel.',looking:'Senior professionals willing to offer students a candid view of leadership decisions and careers.',prior:'The series favors interactive conversations over prepared keynotes.',pitch:'The career moves that teach you to lead change',approach:'Propose a candid fireside chat built around three pivotal decisions and audience Q&A.'},
 {id:6,title:'Enterprise Transformation Advisory Council',org:'Catalyst Expert Network',category:'Paid Advisory / Expert Opportunities',icon:'advisory',score:74,location:'Remote',format:'Remote',value:'Paid',compensation:'$600–$900 / hour',deadline:'Rolling',date:'Quarterly, beginning October',status:'new',new:false,why:'High hourly value and strong expertise fit, balanced by limited information about the end client.',fit:{Expertise:88,Goals:79,Audience:72,Value:95,Probability:57},themes:['Enterprise transformation','Change portfolio strategy','Executive governance'],gaps:'End client is confidential and selection probability is difficult to assess.',looking:'Independent executives with firsthand experience governing multi-year transformation portfolios.',prior:'Not disclosed due to client confidentiality.',pitch:'Practical governance patterns for keeping complex transformation portfolios on track',approach:'Highlight direct operating scope, decision authority, and quantified portfolio outcomes.'}
];
const cats=['All','Conferences','Paid Speaking','Visibility Speaking','Podcasts & Media','Awards & Recognition','Paid Advisory / Expert Opportunities'];
const iconFor=(o,n=18)=>{const P={conference:UsersRound,podcast:Podcast,award:Trophy,mic:Mic2,visibility:Globe2,advisory:BriefcaseBusiness}[o.icon]||Compass;return <P size={n}/>};
const verdict=s=>s>=85?'Strong Pursue':s>=70?'Worth Considering':'Low Priority';

function App(){
 const[view,setView]=useState('dashboard'),[selected,setSelected]=useState(null),[filter,setFilter]=useState('All'),[query,setQuery]=useState('');
 const[state,setState]=useState(()=>JSON.parse(localStorage.getItem('radar-state')||'{}'));
 useEffect(()=>localStorage.setItem('radar-state',JSON.stringify(state)),[state]);
 const status=id=>state[id]||opportunities.find(x=>x.id===id).status;
 const update=(id,s)=>setState(v=>({...v,[id]:s}));
 const rows=useMemo(()=>opportunities.filter(o=>(filter==='All'||o.category===filter)&&(`${o.title} ${o.org}`.toLowerCase().includes(query.toLowerCase()))),[filter,query]);
 const open=o=>{setSelected(o);setView('detail');scrollTo(0,0)};
 return <div className="app"><Sidebar view={view} setView={setView}/><main>
  {view==='dashboard'&&<Dashboard rows={rows} filter={filter} setFilter={setFilter} query={query} setQuery={setQuery} open={open} status={status} update={update}/>} 
  {view==='detail'&&<Detail o={selected} back={()=>setView('dashboard')} status={status(selected.id)} update={s=>update(selected.id,s)}/>} 
  {view==='profile'&&<Profile back={()=>setView('dashboard')}/>} 
 </main></div>
}
function Sidebar({view,setView}){return <aside><div className="brand"><div className="brandmark"><Compass size={21}/></div><span>Opportunity<br/><b>Radar</b></span></div><nav><button className={view==='dashboard'||view==='detail'?'active':''} onClick={()=>setView('dashboard')}><Compass/>Discover</button><button><Bookmark/>Saved</button><button><BriefcaseBusiness/>Pursuing</button></nav><div className="sidefoot"><button className={view==='profile'?'active':''} onClick={()=>setView('profile')}><Settings2/>Profile & preferences</button><div className="user"><div>AM</div><span><b>Alex Morgan</b><small>Transformation Leader</small></span></div></div></aside>}
function Dashboard({rows,filter,setFilter,query,setQuery,open,status,update}){return <><header><div><p className="eyebrow">FRIDAY, SEPTEMBER 11</p><h1>Good morning, Alex.</h1><p>Your radar found <b>12 new opportunities</b> worth a closer look.</p></div><div className="search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search opportunities"/><kbd>⌘ K</kbd></div></header>
<section className="overview"><div className="stat"><span className="statIcon blue"><Sparkles/></span><div><strong>12</strong><p>New this week <span>↑ 4</span></p></div></div><div className="stat"><span className="statIcon green"><ArrowUpRight/></span><div><strong>3</strong><p>Strong pursue <span>Top matches</span></p></div></div><div className="radar"><span><b>Radar last updated</b><small>Today at 6:30 AM</small></span><button><Clock3/> Research activity</button></div></section>
<section className="content"><div className="sectionTitle"><div><h2>Recommended for you</h2><p>Ranked by fit with your expertise, goals, and preferences</p></div><button className="sort"><Settings2/> Best match <ChevronDown/></button></div><div className="filters">{cats.map(c=><button className={filter===c?'active':''} onClick={()=>setFilter(c)} key={c}>{c}</button>)}</div><div className="results"><p><b>{rows.length} opportunities</b> matching your preferences</p>{rows.map(o=><Card key={o.id} o={o} open={open} current={status(o.id)} update={update}/>)}</div></section></>}
function Card({o,open,current,update}){return <article className="card"><div className={'score '+(o.score>=85?'high':'mid')}><strong>{o.score}</strong><small>MATCH</small></div><div className="cardbody"><div className="cardtop"><div className="typeicon">{iconFor(o)}</div><div><span className="category">{o.category}</span><h3>{o.title}</h3><p className="org">{o.org}</p></div><span className={'badge '+(o.value==='Paid'?'paid':o.value.startsWith('Potential')?'potential':'visibility')}>{o.value}</span></div><div className="meta"><span><MapPin/>{o.location}</span><span><CalendarDays/>Deadline {o.deadline}</span>{o.compensation&&<span><BriefcaseBusiness/>{o.compensation}</span>}</div><div className="why"><Sparkles/><span><b>Why you fit</b>{o.why}</span></div><div className="cardfoot"><span className={'verdict '+(o.score>=85?'strong':'consider')}>{o.score>=85&&<Check/>}{verdict(o.score)}</span><div className="actions"><button className={current==='saved'?'selected':''} onClick={()=>update(o.id,'saved')}><Bookmark/>Save</button><button className={current==='pursuing'?'selected pursue':''} onClick={()=>update(o.id,'pursuing')}><ArrowUpRight/>Pursuing</button><button className={current==='passed'?'selected':''} onClick={()=>update(o.id,'passed')}><X/>Pass</button><button className="primary" onClick={()=>open(o)}>View opportunity <ArrowUpRight/></button></div></div></div></article>}
function Detail({o,back,status,update}){return <><div className="detailHead"><button className="back" onClick={back}><ArrowLeft/>Back to opportunities</button><div className="detailTitle"><div className="typeicon large">{iconFor(o,24)}</div><div><span className="category">{o.category}</span><h1>{o.title}</h1><p>{o.org}</p></div></div><div className="detailMeta"><span><CalendarDays/> {o.date}</span><span><MapPin/> {o.location} · {o.format}</span><span className="deadline"><Clock3/> Apply by {o.deadline}</span></div></div><div className="detailGrid"><div className="detailMain"><section className="panel scorePanel"><div className={'bigscore '+(o.score>=85?'high':'mid')}><b>{o.score}</b><small>OVERALL<br/>MATCH</small></div><div><span className="verdict strong">{verdict(o.score)}</span><h2>An opportunity built around your strengths</h2><p>{o.why}</p></div></section><section className="panel"><h2>Why you fit</h2><div className="fitgrid">{Object.entries(o.fit).map(([k,v])=><div className="fit" key={k}><span>{k}<b>{v}</b></span><i><em style={{width:v+'%'}}/></i></div>)}</div><div className="callout"><b>Potential gap</b><p>{o.gaps}</p></div></section><section className="panel"><div className="panelTitle"><span className="statIcon lavender"><Search/></span><div><h2>Research brief</h2><p>What we found to improve your odds</p></div></div><h4>WHAT THEY'RE LOOKING FOR</h4><p>{o.looking}</p><h4>RELEVANT THEMES</h4><div className="tags">{o.themes.map(x=><span>{x}</span>)}</div><h4>WHO THEY'VE FEATURED</h4><p>{o.prior}</p></section><section className="panel approach"><div className="panelTitle"><span className="statIcon amber"><Sparkles/></span><div><h2>Recommended approach</h2><p>A tailored angle based on our research</p></div></div><div className="pitch"><small>SUGGESTED PITCH ANGLE</small><h3>“{o.pitch}”</h3><p>{o.approach}</p></div></section></div><aside className="sidepanel"><div className="panel"><h3>Opportunity details</h3><dl><dt>VALUE TYPE</dt><dd><span className="dot"/> {o.value}</dd>{o.compensation&&<><dt>COMPENSATION</dt><dd>{o.compensation}</dd></>}<dt>DEADLINE</dt><dd>{o.deadline}</dd><dt>FORMAT</dt><dd>{o.format}</dd></dl><a href="https://example.com" target="_blank">View original source <ExternalLink/></a></div><div className="panel"><h3>Your status</h3><div className="statusbuttons"><button className={status==='saved'?'selected':''} onClick={()=>update('saved')}><Bookmark/>Saved</button><button className={status==='pursuing'?'selected pursue':''} onClick={()=>update('pursuing')}><ArrowUpRight/>Pursuing</button><button className={status==='passed'?'selected':''} onClick={()=>update('passed')}><X/>Pass</button></div><p className="hint">Your status is saved automatically.</p></div></aside></div></>}
function Profile({back}){const[p,setP]=useState(()=>JSON.parse(localStorage.getItem('radar-profile')||'{"name":"Alex Morgan","role":"Transformation Leader","location":"New York, NY","expertise":"Organizational transformation, leadership, future of work","topics":"Leading change, culture, executive decision-making","minimum":"5000"}'));const save=()=>{localStorage.setItem('radar-profile',JSON.stringify(p));back()};return <div className="profile"><button className="back" onClick={back}><ArrowLeft/>Back to dashboard</button><p className="eyebrow">YOUR RADAR</p><h1>Profile & preferences</h1><p>We use these details to find and rank the opportunities most relevant to you.</p><section className="panel form"><h2>Professional profile</h2><div className="formgrid">{[['name','Full name'],['role','Current role / title'],['location','Location'],['minimum','Minimum compensation ($)'],['expertise','Areas of expertise'],['topics','Topics you speak about']].map(([k,l])=><label className={k==='expertise'||k==='topics'?'wide':''}>{l}{k==='expertise'||k==='topics'?<textarea value={p[k]} onChange={e=>setP({...p,[k]:e.target.value})}/>:<input value={p[k]} onChange={e=>setP({...p,[k]:e.target.value})}/>}</label>)}</div><h3>Primary goals</h3><div className="checkrow">{['Income','Visibility','Credibility','Networking','Career growth'].map(x=><button className="selected"><Check/>{x}</button>)}</div><div className="savebar"><button className="primary" onClick={save}>Save preferences</button></div></section></div>}
createRoot(document.getElementById('root')).render(<App/>);
